name: DiamondShards
main: net.LoadingChunks.DiamondShards.DiamondShards
version: 0.1

commands:
   su:
      description: Executes command on another server
      usage: /<command> <server> <command>
